- type: job
  id: TownSheriff # Renamed to "Marshal", don't touch the prototype ID
  setPreference: true
  jobWhitelistBypassesRoleTimers: true
  weight: 80
  showBorder: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-townsheriff
  description: job-description-townsheriff
  playTimeTracker: TownSheriff
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
      - GhoulGlowing
    - !type:CharacterDepartmentTimeRequirement # #Misfits Tweak - re-enable timelock, 10h Townsfolk requirement
      department: Townsfolk
      min: 36000 # 10 hours
  startingGear: TownSheriffGear
  icon: "JobIconTownSheriff" # Corvax-Change
  supervisors: job-supervisors-townsfolk
  access:
  - TownieLaw
  - TownieMechanic
  - TownieDoctor
  - WastelandReporter
  - TownsPerson # Corvax-Change
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Townsfolk

- type: startingGear
  id: TownSheriffGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTownGuardLight
    ears: MisfitsClothingHeadsetWastelandScrap
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDBadgeTownSheriff
    belt: ClothingBeltRevolverWildWhisper
    pocket1: TownGuardKits
    pocket2: Handcuffs
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: TownSheriff
