- type: job
  id: NCRPrisoner
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 1
  showBorder: false
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-ncr-prisoner #Misfits Change
  description: job-description-ncr-prisoner
  playTimeTracker: NCRPrisoner
  requirements: # TEMP REMOVED - all requirements removed
   # - !type:MinPlayersRequirement
   #   min: 55
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
   # - !type:CharacterOverallTimeRequirement
   #   min: 3600
  startingGear: NCRPrisonerGear
  icon: "JobIconNCRPrisoner"
  supervisors: job-supervisors-ncr-prisoners
  alwaysUseSpawner: true
  access:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRPrisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: N14ClothingShoesBlack
    bandage: NCClothingBraceletNCRPrisoner

- type: playTimeTracker
  id: NCRPrisoner
