- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionLegate
  name: Legate
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionLegateGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionCenturion
  name: Legion Centurion
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionCenturionGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionVeteranDecanus
  name: Veteran Decanus
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionVeteranDecanusGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionFrumentarii
  name: Frumentarii
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionFrumentariiGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionPrimeDecanus
  name: Prime Decanus
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionPrimeDecanusGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionVexillarius
  name: Vexillarius
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionVexillariusGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionExplorer
  name: Legion Explorer
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionExplorerGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionOptio
  name: Legion Optio
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionOptioGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionDean
  name: Legion Decanus
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionDeanGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionnaireVeteran
  name: Veteran Legionary
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionLegionnaireVeteranGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionnaireWarrior
  name: Prime Legionary
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionLegionnaireWarriorGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionnaireRecruit
  name: Recruit Legionary
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionLegionnaireRecruitGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionHoundmaster
  name: Houndmaster
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionHoundmasterGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarLegionRecruit
  name: Recruit
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionLegionnaireRecruitGear] # #Misfits Change: Redirected from defunct CaesarLegionRecruitGear
    - type: NpcFactionMember
      factions:
      - CaesarLegion

- type: entity
  parent: MobHuman
  id: N14MobHumanCaesarCaesarLegionSlave
  name: Legion Slave
  components:
    - type: RandomHumanoidAppearance
      randomizeName: true
    - type: Loadout
      prototypes: [CaesarLegionSlaveGear]
    - type: NpcFactionMember
      factions:
      - CaesarLegion
