using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Nuclear14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsProductCard : BoxContainer
{
    public int CategoryIndex { get; set; }
    public int EntryIndex { get; set; }
    public int UnitCost { get; set; }

    public RequisitionsProductCard()
    {
        RobustXamlLoader.Load(this);
        RequisitionsUiStyles.ApplyQuantityButton(RemoveButton);
        RequisitionsUiStyles.ApplyQuantityButton(AddButton);
        RequisitionsUiStyles.ApplyQuantityButton(Add10Button);
        RequisitionsUiStyles.ApplyQuantityButton(MaxButton);
        Cost.Modulate = RequisitionsUiStyles.Green;
        Quantity.Modulate = RequisitionsUiStyles.Green;
    }
}
