using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Nuclear14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsPendingOrderCard : BoxContainer
{
    public RequisitionsPendingOrderCard()
    {
        RobustXamlLoader.Load(this);
        Cost.Modulate = RequisitionsUiStyles.Green;
        Quantity.Modulate = RequisitionsUiStyles.Green;
    }
}
