using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Nuclear14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsCartRow : BoxContainer
{
    public int CategoryIndex { get; set; }
    public int EntryIndex { get; set; }
    public int UnitCost { get; set; }

    public RequisitionsCartRow()
    {
        RobustXamlLoader.Load(this);
        RequisitionsUiStyles.ApplyQuantityButton(RemoveButton);
        RequisitionsUiStyles.ApplyQuantityButton(AddButton);
        Cost.Modulate = RequisitionsUiStyles.Green;
        Quantity.Modulate = RequisitionsUiStyles.Green;
    }
}
