using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Timing;

namespace Content.Client._Nuclear14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private TimeSpan? _busyStart;
    private TimeSpan? _busyEnd;

    public RequisitionsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Stylesheet = RequisitionsUiStyles.Create();
        ShopTabs.StyleClasses.Add(RequisitionsUiStyles.ShopTabs);

        foreach (var btn in new[] { PlatformButton, ClearCartButton, BuyButton, SellRefreshButton, WithdrawButton, PrintHistoryButton })
            RequisitionsUiStyles.ApplyQuantityButton(btn);

        foreach (var (tab, key) in new (Control, string)[]
        {
            (ProductsTab,  "n14-requisitions-tab-products"),
            (CartTab,      "n14-requisitions-tab-cart"),
            (SellTab,      "n14-requisitions-tab-sell"),
            (StorageTab,   "n14-requisitions-tab-storage"),
            (PendingTab,   "n14-requisitions-tab-pending"),
            (HistoryTab,   "n14-requisitions-tab-history"),
            (BountiesTab,  "n14-requisitions-tab-bounties"),
        })
            TabContainer.SetTabTitle(tab, Loc.GetString(key));
    }

    public void SetPlatformBusy(TimeSpan? start, TimeSpan? end)
    {
        _busyStart = start;
        _busyEnd = end;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_busyStart is not { } start || _busyEnd is not { } end || end <= start)
        {
            PlatformProgress.Visible = false;
            return;
        }

        var now = _timing.CurTime;
        var fraction = (float) ((now - start) / (end - start));
        PlatformProgress.Value = System.Math.Clamp(fraction, 0f, 1f);
        PlatformProgress.Visible = fraction is >= 0f and < 1f;
    }
}
