using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Nuclear14.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsProductCard : BoxContainer
{
    public int CategoryIndex { get; set; }
    public int EntryIndex { get; set; }
    public int UnitCost { get; set; }

    public RequisitionsProductCard()
    {
        RobustXamlLoader.Load(this);
        foreach (var btn in new[] { RemoveButton, AddButton, MaxButton })
            RequisitionsUiStyles.ApplyQuantityButton(btn);
        Cost.Modulate = RequisitionsUiStyles.Green;
        Quantity.Modulate = RequisitionsUiStyles.Green;
        MouseFilter = MouseFilterMode.Pass;
    }
}
