// #Misfits Add - Code-behind for the Faction War GUI panel.
// Handles population of faction dropdowns, the active-wars list,
// result feedback, confirm-to-declare flow, and fires events back to FactionWarClientSystem.

using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.FactionWar.UI;

/// <summary>
/// Faction War panel window. Allows eligible players to declare war on,
/// or declare a ceasefire with, another faction.
/// All game-logic validation is done server-side; this window only collects input
/// and displays feedback from <see cref="FactionWarClientSystem"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FactionWarWindow : FancyWindow
{
    // ── Events fired back to FactionWarClientSystem ────────────────────────

    /// <summary>Fired when the player confirms Declare War. Args: (targetFactionId, casusBelli).</summary>
    public event Action<string, string>? OnDeclareWar;

    /// <summary>Fired when the player clicks Propose Ceasefire. Args: targetFactionId.</summary>
    public event Action<string>? OnCeasefire;

    /// <summary>Fired when the player accepts an incoming ceasefire proposal. Args: (aggressorFactionId, targetFactionId).</summary>
    public event Action<string, string>? OnAcceptCeasefireProposal;

    /// <summary>Fired when the player rejects an incoming ceasefire proposal. Args: (aggressorFactionId, targetFactionId).</summary>
    public event Action<string, string>? OnRejectCeasefireProposal;

    // ── Internal state ─────────────────────────────────────────────────────

    private readonly List<(string Display, string Id)> _targetFactionItems = new();
    private readonly List<(string Display, string Id)> _ceasefireItems     = new();

    /// <summary>Whether the declare war button is in the "confirm" state (second press fires).</summary>
    private bool _confirmPending;

    private FactionWarCeasefireProposalInfo? _pendingCeasefireProposal;

    // ── Constructor ────────────────────────────────────────────────────────

    public FactionWarWindow()
    {
        RobustXamlLoader.Load(this);

        // Populate rules text — hardcoded markup because FTL can't have lines starting with '['.
        RulesLabel.SetMarkup(
            "[bold]6.3 - Faction Warfare Rules[/bold]\n" +
            "[bullet]Factions begin [bold]neutral[/bold].[/bullet]\n" +
            "[bullet]Highest Rank may declare war.[/bullet]\n" +
            "[bullet]War begins [bold]five minutes[/bold] after declaration.[/bullet]\n" +
            "[bullet]Killing diplomats or surrendered individuals is [bold]forbidden[/bold].[/bullet]\n" +
            "[bullet]You must prioritize taking [bold]slaves / prisoners[/bold].[/bullet]\n" +
            "[bullet]No intentionally round-ending someone (de-heading, gibbing, etc.).[/bullet]\n" +
            "[bullet]Highest-ranking member may be round-removed [bold]only[/bold] via RP-friendly means (e.g., public execution).[/bullet]");

        DeclareWarButton.OnPressed += _ => OnDeclareWarPressed();
        CeasefireButton.OnPressed  += _ => SubmitCeasefire();

        AcceptCeasefireProposalButton.OnPressed += _ => SubmitAcceptCeasefireProposal();
        RejectCeasefireProposalButton.OnPressed += _ => SubmitRejectCeasefireProposal();

        // Commit dropdown selection and reset confirm state when the target changes.
        TargetFactionSelector.OnItemSelected += args => { TargetFactionSelector.SelectId(args.Id); ResetConfirm(); };
        CeasefireTargetSelector.OnItemSelected += args => CeasefireTargetSelector.SelectId(args.Id);
    }

    // ── Public API called by FactionWarClientSystem ────────────────────────

    /// <summary>
    /// Refresh all window state. Call whenever the local war list changes or the window is first opened.
    /// </summary>
    public void UpdateState(
        string? myFactionId,
        string myFactionDisplay,
        IReadOnlyList<FactionWarEntry> activeWars,
        IReadOnlyList<(string Display, string Id)> eligibleTargets,
        IReadOnlyList<(string Display, string Id)> ceasefireTargets,
        IReadOnlyList<FactionWarCeasefireProposalInfo> incomingCeasefireProposals)
    {
        // ── "Your Faction" label ──────────────────────────────────────────
        MyFactionLabel.Text = myFactionId == null
            ? Loc.GetString("faction-war-no-faction")
            : myFactionDisplay;

        // ── Active-wars list ──────────────────────────────────────────────
        ActiveWarsContainer.RemoveAllChildren();
        if (activeWars.Count == 0)
        {
            var noWars = new Label
            {
                Text = Loc.GetString("faction-war-no-active-wars"),
                FontColorOverride = Color.Gray,
                Margin = new Thickness(4, 2),
            };
            ActiveWarsContainer.AddChild(noWars);
        }
        else
        {
            foreach (var war in activeWars)
            {
                var phaseTag = war.Phase == WarPhase.Pending ? "[PENDING] " : "";
                var entry = new Label
                {
                    Text   = $"{phaseTag}{FactionWarConfig.FactionDisplayName(war.AggressorFaction)}" +
                             $" vs {FactionWarConfig.FactionDisplayName(war.TargetFaction)}" +
                             $" - \"{war.CasusBelli}\"",
                    Margin            = new Thickness(4, 2),
                    ClipText          = true,
                    HorizontalExpand  = true,
                };
                ActiveWarsContainer.AddChild(entry);
            }
        }

        // ── Target faction selector (Declare War) ─────────────────────────
        _targetFactionItems.Clear();
        TargetFactionSelector.Clear();

        foreach (var (display, id) in eligibleTargets)
        {
            _targetFactionItems.Add((display, id));
            TargetFactionSelector.AddItem(display);
        }

        DeclareWarButton.Disabled = eligibleTargets.Count == 0 || myFactionId == null;
        ResetConfirm();

        // ── Ceasefire selector ────────────────────────────────────────────
        _ceasefireItems.Clear();
        CeasefireTargetSelector.Clear();

        foreach (var (display, id) in ceasefireTargets)
        {
            _ceasefireItems.Add((display, id));
            CeasefireTargetSelector.AddItem(display);
        }

        CeasefireButton.Disabled = ceasefireTargets.Count == 0 || myFactionId == null;

        // ── Incoming Ceasefire Proposal ───────────────────────────────────
        _pendingCeasefireProposal = incomingCeasefireProposals.Count > 0 ? incomingCeasefireProposals[0] : null;
        IncomingCeasefireProposalSection.Visible = _pendingCeasefireProposal != null;
        if (_pendingCeasefireProposal != null)
        {
            var reqDisplay = FactionWarConfig.FactionDisplayName(_pendingCeasefireProposal.RequestingFaction);
            IncomingCeasefireProposalLabel.Text = $"{reqDisplay} proposes a ceasefire.";
            IncomingCeasefireProposerLabel.Text = $"Proposed by: {_pendingCeasefireProposal.RequesterCharacterName}, {_pendingCeasefireProposal.RequesterJobName}";
        }

        // Clear any previous result message when state refreshes.
        ClearResult();
    }

    /// <summary>Display a success or error message in the result label (supports wrapping).</summary>
    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        ResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    // ── Private helpers ────────────────────────────────────────────────────

    /// <summary>
    /// First press: validate and switch to confirm state. Second press: fire the event.
    /// </summary>
    private void OnDeclareWarPressed()
    {
        if (TargetFactionSelector.ItemCount == 0)
            return;

        var idx = TargetFactionSelector.SelectedId;
        if (idx < 0 || idx >= _targetFactionItems.Count)
            return;

        var casusBelli = CasusBelliEdit.Text.Trim();

        if (casusBelli.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length < 5)
        {
            ShowResult(false, Loc.GetString("faction-war-casus-belli-too-short"));
            return;
        }

        if (!_confirmPending)
        {
            // First press — switch to confirmation state.
            _confirmPending = true;
            DeclareWarButton.Text = Loc.GetString("faction-war-confirm-button");
            DeclareWarButton.Modulate = Color.OrangeRed;
            ShowResult(false, Loc.GetString("faction-war-confirm-prompt"));
            return;
        }

        // Second press — confirmed, fire the event.
        var targetId = _targetFactionItems[idx].Id;
        OnDeclareWar?.Invoke(targetId, casusBelli);
        ResetConfirm();
    }

    private void ResetConfirm()
    {
        _confirmPending = false;
        DeclareWarButton.Text = Loc.GetString("faction-war-declare-button");
        DeclareWarButton.Modulate = Color.White;
    }

    private void SubmitCeasefire()
    {
        if (CeasefireTargetSelector.ItemCount == 0)
            return;

        var idx = CeasefireTargetSelector.SelectedId;
        if (idx < 0 || idx >= _ceasefireItems.Count)
            return;

        var targetId = _ceasefireItems[idx].Id;
        OnCeasefire?.Invoke(targetId);
    }

    private void ClearResult()
    {
        ResultLabel.SetMarkup(string.Empty);
    }

    private void SubmitAcceptCeasefireProposal()
    {
        if (_pendingCeasefireProposal == null)
            return;
        OnAcceptCeasefireProposal?.Invoke(_pendingCeasefireProposal.AggressorFaction, _pendingCeasefireProposal.TargetFaction);
    }

    private void SubmitRejectCeasefireProposal()
    {
        if (_pendingCeasefireProposal == null)
            return;
        OnRejectCeasefireProposal?.Invoke(_pendingCeasefireProposal.AggressorFaction, _pendingCeasefireProposal.TargetFaction);
    }
}
