- type: job
  id: Overseer
  name: job-name-overseer
  description: job-description-overseer
  hideWithoutJobWhitelist: false # #Misfits Tweak - no whitelist gate
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - always visible
  jobWhitelistBypassesRoleTimers: true # #Misfits Change - open to all
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterDepartmentTimeRequirement # #Misfits Tweak - reduced from 70h to 40h, inline with other faction leadership locks
    department: Vault
    min: 144000 # 40 hours
  playTimeTracker: Overseer
  weight: 100
  startingGear: OverseerGear
  alwaysUseSpawner: true
  icon: "JobIconVaultOverseer" # Forge-Change
  requireAdminNotify: true
  joinNotifyCrew: true
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  overwatchCategory: OverwatchCommand
  supervisors: job-supervisors-vault-overseer
  accessGroups:
  - VaultOverseer
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Vault

- type: startingGear
  id: OverseerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultBlue # Forge-Change
    shoes: N14ClothingBootsBlack
    eyes: ClothingEyesGlassesSunglasses
    id: N14VaultOverseerPDA
    ears: N14ClothingHeadsetVaultDweller
    pocket1: N14WeaponPistol10mm
  innerClothingSkirt: N14ClothingUniformJumpsuitVault14
  storage: # Forge-Change
    back:
    - N14Bandage
    - N14CurrencyPrewarMoney500
    - N14CurrencyPrewarMoney500
    - VaultGuidePaper
- type: playTimeTracker
  id: Overseer
