- type: job
  id: VaultSecurity
  weight: 80
  showBorder: true
  hideWithoutJobWhitelist: false # #Misfits Tweak - no whitelist gate
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - always visible
  jobWhitelistBypassesRoleTimers: true # #Misfits Change - open to all
  name: job-name-vault-security
  description: job-description-vault-security
  playTimeTracker: VaultSecurity
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  #- !type:CharacterDepartmentTimeRequirement # TEMP REMOVED
  #  department: Vault
  #  min: 36000 # 10 hours
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  startingGear: VaultSecurityGear
  alwaysUseSpawner: true
  icon: "JobIconVaultSecurity" # Forge-Change
  supervisors: job-supervisors-vault
  access:
  - VaultDweller
  - VaultSecurity
  - VaultEngineer
  - VaultMedical
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Vault

- type: startingGear
  id: VaultSecurityGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultBlue # Forge-Change
    shoes: N14ClothingBootsBlack
    eyes: N14ClothingEyesSunGlasses
    head: N14ClothingHeadHatVaultRiot
    outerClothing: N14ClothingOuterVaultSecVest
    id: N14VaultSecurityPDA
    pocket1: N14WeaponPistol10mm
    pocket2: Handcuffs
    ears: N14ClothingHeadsetVaultDweller
    belt: N14PoliceBaton
  storage: # Forge-Change
    back:
    - N14Bandage
    - N14CurrencyPrewarMoney100
    - N14CurrencyPrewarMoney100
    - N14CurrencyPrewarMoney100
    - N14MagazinePistol10mm
    - N14MagazinePistol10mm
    - VaultGuidePaper
- type: playTimeTracker
  id: VaultSecurity
