- type: job
  id: WastelandFarmer
  setPreference: true
  weight: 30
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-farmer
  description: job-description-farmer
  playTimeTracker: Farmer
  startingGear: FarmerGear
  icon: "JobIconWastelandFarmer" # Corvax-Change
  supervisors: job-supervisors-wastelander
  requirements: # #Misfits Change - robots and supermutants cannot be Farmers
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
      - RobotMrHandy
      - RobotProtectron
      - RobotProtectronPolice # #Misfits Fix - missing variant species
      - RobotProtectronBuilder # #Misfits Fix - missing variant species
      - RobotProtectronFire # #Misfits Fix - missing variant species
      - RobotMrGutsy
      - RobotAssaultron
      - RobotAssaultronTesla # #Misfits Fix - missing variant species
      - RobotSentryBot # #Misfits Fix - missing robot chassis
      - RobotSentryBotLaser # #Misfits Fix - missing variant species
      - RobotRobobrain # #Misfits Fix - missing robot chassis
      - RobotRobobrainLaser # #Misfits Fix - missing variant species
      - SuperMutant #Misfits Change /Add: SuperMutants cannot be Town Farmers
      - Nightkin
  access:
  - WastelandFarmer
  - TownsPerson # Corvax-Change

- type: startingGear
  id: FarmerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBrahminFarmer
    ears: MisfitsClothingHeadsetWastelandScrap
    back: N14ClothingBackpackExplorer # Corvax-Change
    shoes: N14ClothingBootsLeather
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltFarmerFilled
    id: N14IDPassportWasteFarmer
  innerClothingSkirt: N14ClothingUniformJumpsuitBrahminFarmer #placeholder
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: Farmer
