using System.Linq;
using Content.Client.Humanoid;
using Content.Client.Stylesheets;
using Content.Shared.Clothing;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI;

/// Holds character data on the side of the setup GUI
[GenerateTypedNameReferences]
public sealed partial class CharacterPickerButton : ContainerButton
{
    private IEntityManager _entManager;

    private EntityUid _previewDummy;

    /// Invoked if we should delete the attached character
    public event Action? OnDeletePressed;

    public CharacterPickerButton(
        IEntityManager entityManager,
        IPrototypeManager prototypeManager,
        ButtonGroup group,
        ICharacterProfile profile,
        bool isSelected)
    {
        RobustXamlLoader.Load(this);
        _entManager = entityManager;
        AddStyleClass(StyleClassButton);
        AddStyleClass(StyleNano.StyleClassPipBoyButton);
        ToggleMode = true;
        Group = group;
        var description = profile.Name;

        if (profile is not HumanoidCharacterProfile humanoid)
        {
            _previewDummy = entityManager.SpawnEntity(prototypeManager.Index<SpeciesPrototype>(SharedHumanoidAppearanceSystem.DefaultSpecies).DollPrototype, MapCoordinates.Nullspace);
        }
        else
        {
            _previewDummy = UserInterfaceManager.GetUIController<LobbyUIController>()
                .LoadProfileEntity(humanoid, true, true);

            var highPriorityJobs = humanoid.JobPriorities
                .Where(p => p.Value == JobPriority.High)
                .Select(p => p.Key)
                .Distinct()
                .ToList();

            if (highPriorityJobs.Count > 0)
            {
                var jobNames = highPriorityJobs
                    .Select(jobId => prototypeManager.Index<JobPrototype>(jobId).LocalizedName)
                    .ToList();
                description = $"{description}\n{string.Join(", ", jobNames)}";
            }
        }

        Pressed = isSelected;
        DeleteButton.Visible = !isSelected;

        View.SetEntity(_previewDummy);
        DescriptionLabel.Text = description;

        ConfirmDeleteButton.OnPressed += _ =>
        {
            Parent?.RemoveChild(this);
            Parent?.RemoveChild(ConfirmDeleteButton);
            OnDeletePressed?.Invoke();
        };

        DeleteButton.OnPressed += _ =>
        {
            DeleteButton.Visible = false;
            ConfirmDeleteButton.Visible = true;
        };
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        _entManager.DeleteEntity(_previewDummy);
        _previewDummy = default;
    }
}
