using Content.Client.Guidebook;
using Content.Client.Guidebook.RichText;
using Content.Client.UserInterface.Systems.Info;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
// #Misfits Add - IUriOpener is in Robust.Client.UserInterface (removed wrong Robust.Shared.Utility import)

namespace Content.Client.Info;

[GenerateTypedNameReferences]
public sealed partial class RulesControl : BoxContainer, ILinkClickHandler
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!; // #Misfits Add - open external URLs from textlinks

    private string? _currentEntry;
    private readonly Stack<string> _priorEntries = new();

    public RulesControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetGuide();

        OpenRulesButton.OnPressed += _ => _uriOpener.OpenUri("https://wiki.misfitsystems.net/index.php/Rules");

        HomeButton.OnPressed += _ => SetGuide();

        BackButton.OnPressed += _ => SetGuide(_priorEntries.Pop(), false);
    }

    public void HandleClick(string link)
    {
        // #Misfits Add - detect external URLs (e.g., wiki links) and open in browser
        if (link.StartsWith("https://", StringComparison.OrdinalIgnoreCase) ||
            link.StartsWith("http://", StringComparison.OrdinalIgnoreCase))
        {
            _uriOpener.OpenUri(link);
            return;
        }
        SetGuide(link);
    }

    private void SetGuide(ProtoId<GuideEntryPrototype>? entry = null, bool addToPrior = true)
    {
        var coreEntry = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        entry ??= coreEntry;

        Scroll.SetScrollValue(default);
        RulesContainer.Children.Clear();
        if (!_parsingMan.TryAddMarkup(RulesContainer, entry.Value))
        {
            // Fallback: show a simple message and open the live rules in the browser.
            var fallbackRoot = new Control
            {
                HorizontalExpand = true,
                VerticalExpand = true
            };

            var fallbackBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = HAlignment.Center,
                VerticalExpand = false,
                MaxWidth = 700,
                Margin = new Thickness(4)
            };

            var fallback = new Label
            {
                Text = "Rules are available on the Misfits wiki. Click the button to open the live rules in your browser.",
                HorizontalExpand = true,
                VerticalExpand = false,
                MaxWidth = 600,
                ClipText = false,
                Align = Label.AlignMode.Center,
                Margin = new Thickness(4)
            };

            var openButton = new Button
            {
                Text = "Open Live Rules",
                HorizontalAlignment = HAlignment.Center,
                TextAlign = Label.AlignMode.Center,
                MinWidth = 160,
                MaxWidth = 260,
                Margin = new Thickness(4)
            };

            openButton.OnPressed += _ => _uriOpener.OpenUri("https://wiki.misfitsystems.net/index.php/Rules");

            fallbackBox.AddChild(fallback);
            fallbackBox.AddChild(openButton);
            fallbackRoot.AddChild(fallbackBox);
            RulesContainer.AddChild(fallbackRoot);
            return;
        }

        if (addToPrior && _currentEntry != null)
            _priorEntries.Push(_currentEntry);
        _currentEntry = entry.Value;

        HomeButton.Visible = entry.Value != coreEntry.Id;
        BackButton.Visible = _priorEntries.Count != 0 && _priorEntries.Peek() != entry.Value;
    }
}
