using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared._Misfits.Holotape;
using Content.Shared._Misfits.Overwatch;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Maths;
using Robust.Shared.Network;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

// #Misfits Add - Code-behind for the holotape/terminal viewer window.
// Renders content in green monospace text on a black background.
// #Misfits Add - Tab switching between DATA and NOTES views.

namespace Content.Client._Misfits.Holotape;

/// <summary>
/// Green-on-black terminal-style window for reading holotapes and terminal entries.
/// Supports a NOTES tab for persistent player-written notes on terminals.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HolotapeWindow : DefaultWindow
{
    // Vault-Tec terminal green
    private const string TermGreen = "#33FF33";
    private const string TermDimGreen = "#1a5c1a";

    // Events fired to the BUI for message sending
    /// <summary>Fired when the user clicks Submit Note.</summary>
    public event Action<string, string>? OnSubmitNote;

    /// <summary>Fired when the user clicks delete on a note. Carries the note Guid.</summary>
    public event Action<Guid>? OnDeleteNote;

    /// <summary>Fired when the user switches to the Notes tab (requests fresh data).</summary>
    public event Action? OnRequestNotes;

    // #Misfits Add - Fired when the user clicks a link port button in the LINKS tab.
    /// <summary>Fired when the user clicks a link port toggle button. Carries the port ID string.</summary>
    public event Action<string>? OnInvokeLinkPort;

    // #Misfits Add - Database BUI events. Wired by HolotapeBoundUserInterface to send messages.
    public event Action? OnRequestDatabase;
    public event Action<Guid>? OnOpenDatabaseDocument;
    public event Action<Guid?, string, bool>? OnCreateDatabaseFolder;    // parentFolderId (null=top), name, markAsAdmin (root only)
    public event Action<Guid, Guid?, string, string, bool>? OnCreateDatabaseDocument; // folderId, subfolderId, title, body, markAdmin
    public event Action<Guid, string>? OnEditDatabaseDocument;           // documentId, body
    public event Action<Guid, Guid?>? OnDeleteDatabaseFolder;            // folderId, subfolderId
    public event Action<Guid>? OnDeleteDatabaseDocument;
    public event Action<Guid, int>? OnRollbackDatabaseDocument;
    public event Action<Guid?, Guid?, Guid?, Guid?>? OnRestoreDatabaseEntry;
    // #Misfits Add - Export the currently-open database document to a holotape entity in the actor's hand.
    public event Action<Guid>? OnExportDatabaseDocument;
    public event Action<OverwatchConsoleMessageType, uint?>? OnOverwatchAction;

    /// <summary>Whether we're currently showing the notes tab.</summary>
    private bool _showingNotes;

    /// <summary>The viewer's own user ID, used to show delete buttons on own notes.</summary>
    private NetUserId? _viewerUserId;

    /// <summary>Whether this terminal has notebook capability (controls tab bar visibility).</summary>
    private bool _hasNotebook;

    // #Misfits Add - Whether this terminal has device link source (controls LINKS tab visibility)
    /// <summary>Whether this terminal has a DeviceLinkSourceComponent (controls LINKS tab visibility).</summary>
    private bool _hasLinkSource;
    private bool _hasOverwatch;
    private OverwatchConsoleState? _overwatchState;
    private IEye? _overwatchSourceEye;
    private readonly Dictionary<string, bool> _overwatchGroupExpanded = new();
    private readonly FixedEye _overwatchDefaultEye = new();
    private readonly FixedEye _overwatchFeedEye = new();

    // #Misfits Add - Database state cache (latest server push). Used by all DB rendering paths.
    private TerminalDatabaseState? _databaseState;
    private bool _hasDatabase;

    // Database navigation state — purely client-side breadcrumb / view selector.
    private enum DbView { FolderList, SubfolderList, DocumentList, DocumentViewer, EditorCreateFolder, EditorCreateDoc, EditorEditDoc }
    private DbView _dbView = DbView.FolderList;
    private Guid? _dbCurrentFolder;       // selected top-level folder
    private Guid? _dbCurrentSubfolder;    // selected subfolder (null = browsing folder root)
    private Guid? _dbEditingDocumentId;   // when editing an existing doc
    private Guid? _dbEditorParentFolder;  // for create-folder (null parent = top-level)

    public Content.Client.Viewport.ScalingViewport OverwatchFeedViewport => OverwatchCameraView;

    public HolotapeWindow()
    {
        RobustXamlLoader.Load(this);

        // Apply terminal-style backgrounds programmatically
        BackgroundPanel.PanelOverride = new StyleBoxFlat(Color.FromHex("#0a0a0a"));
        SepTop.PanelOverride = new StyleBoxFlat(Color.FromHex("#1a5c1a"));
        SepMid.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepBot.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepNotes.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        // #Misfits Add - Separator styling for the LINKS tab
        SepLinks.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        // #Misfits Add - Separator styling for the DATABASE tab
        SepDatabase.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepDatabaseActions.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepOverwatch.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        OverwatchCameraFallback.PanelOverride = new StyleBoxFlat(Color.FromHex("#050805"));
        OverwatchCameraView.ViewportSize = new Vector2i(640, 360);
        OverwatchCameraView.Eye = _overwatchDefaultEye;
        LayoutContainer.SetAnchorPreset(OverwatchCameraView, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(OverwatchCameraFallback, LayoutContainer.LayoutPreset.Wide);

        // Tab button styling
        DataTabButton.OnPressed += _ => SwitchToDataTab();
        NotesTabButton.OnPressed += _ => SwitchToNotesTab();
        // #Misfits Add - Wire the Links tab button
        LinksTabButton.OnPressed += _ => SwitchToLinksTab();
        // #Misfits Add - Wire the Database tab button
        DatabaseTabButton.OnPressed += _ => SwitchToDatabaseTab();
        OverwatchTabButton.OnPressed += _ => SwitchToOverwatchTab();
        OverwatchStopWatchingButton.OnPressed += _ => OnOverwatchAction?.Invoke(OverwatchConsoleMessageType.Unwatch, null);
        OverwatchSearchBar.OnTextChanged += _ => RefreshOverwatchView();

        // Submit button
        SubmitNoteButton.OnPressed += _ => HandleSubmit();

        // #Misfits Add - Wire database editor save/cancel buttons
        DatabaseEditorSubmitButton.OnPressed += _ => HandleDatabaseEditorSubmit();
        DatabaseEditorCancelButton.OnPressed += _ => HandleDatabaseEditorCancel();

        // #Misfits Add - Wire the BBCode toolbar. Each button wraps the current selection
        // (or inserts at the cursor with caret placed inside the tag pair).
        BBBoldButton.OnPressed += _ => WrapBBCode("[bold]", "[/bold]");
        BBItalicButton.OnPressed += _ => WrapBBCode("[italic]", "[/italic]");
        BBHead2Button.OnPressed += _ => WrapBBCode("[head=2]", "[/head]");
        BBBulletButton.OnPressed += _ => WrapBBCode("[bullet] ", string.Empty);
        BBColorButton.OnPressed += _ => WrapBBCode("[color=#33FF33]", "[/color]");
        BBClearButton.OnPressed += _ => StripBBCode();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        SyncOverwatchFeedEye();
    }

    // ── Public API ───────────────────────────────────────────────────────────

    /// <summary>
    /// Switches the window header and title bar between holotape-item mode and terminal mode.
    /// Holotape items display "HOLOTAPE PLAYER"; built-in terminals display "TERMLINK PROTOCOL".
    /// </summary>
    // #Misfits Add - Dynamic header switch: HOLOTAPE item vs built-in TERMINAL
    public void SetHolotapeMode(bool isHolotapeItem)
    {
        if (isHolotapeItem)
        {
            Title = "HOLOTAPE";
            HeaderLabel.Text = "ROBCO INDUSTRIES (TM) HOLOTAPE PLAYER";
        }
        else
        {
            Title = "TERMINAL";
            HeaderLabel.Text = "ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL";
        }
    }

    /// <summary>
    /// Updates both the title and body content labels with green terminal text.
    /// </summary>
    public void UpdateContent(string title, string content)
    {
        // Build title message with green color
        var titleMsg = new FormattedMessage();
        if (!string.IsNullOrEmpty(title))
        {
            titleMsg.PushColor(Color.FromHex(TermGreen));
            titleMsg.AddMarkupPermissive($"[bold]> {title}[/bold]");
            titleMsg.Pop();
        }
        EntryTitleLabel.SetMessage(titleMsg);

        // Build content message with green color
        var contentMsg = new FormattedMessage();
        if (!string.IsNullOrEmpty(content))
        {
            contentMsg.PushColor(Color.FromHex(TermGreen));
            contentMsg.AddMarkupPermissive(content);
            contentMsg.Pop();
        }
        ContentLabel.SetMessage(contentMsg);
    }

    /// <summary>
    /// Updates the notes list display and enables the tab bar.
    /// Called when state includes notes (terminal has TerminalNotebookComponent).
    /// </summary>
    public void UpdateNotes(List<TerminalNoteEntry>? notes, NetUserId? viewerUserId)
    {
        _viewerUserId = viewerUserId;
        _hasNotebook = notes != null;

        // Show/hide tab bar depending on whether this terminal has a notebook, links, or database
        TabBar.Visible = _hasNotebook || _hasLinkSource || _hasDatabase || _hasOverwatch;
        NotesTabButton.Visible = _hasNotebook;

        if (notes == null)
        {
            // No notebook — make sure we're on the data tab
            SwitchToDataTab();
            return;
        }

        // Rebuild the notes list UI
        RebuildNotesList(notes);
    }

    // #Misfits Add - Populates the LINKS tab with one button per device link source port.
    // Each button fires OnInvokeLinkPort with the port ID, which the BUI sends to the server.
    /// <summary>
    /// Updates the links list display. Called when state includes device link source data.
    /// </summary>
    public void UpdateLinks(bool hasLinkSource, List<string>? portIds)
    {
        _hasLinkSource = hasLinkSource;
        LinksTabButton.Visible = _hasLinkSource;

        // Update tab bar visibility: show if notebook OR links OR database present
        TabBar.Visible = _hasNotebook || _hasLinkSource || _hasDatabase || _hasOverwatch;

        LinksList.RemoveAllChildren();

        if (!hasLinkSource || portIds == null || portIds.Count == 0)
        {
            if (LinksPanel.Visible)
                SwitchToDataTab();
            return;
        }

        foreach (var portId in portIds)
        {
            var capturedId = portId; // capture for lambda closure

            // Row container: port label + trigger button
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                HorizontalExpand = true,
            };

            // Port name label in terminal green
            var label = new RichTextLabel { HorizontalExpand = true };
            var labelMsg = new FormattedMessage();
            labelMsg.PushColor(Color.FromHex(TermGreen));
            labelMsg.AddMarkupPermissive($"[bold]> {portId}[/bold]");
            labelMsg.Pop();
            label.SetMessage(labelMsg);
            row.AddChild(label);

            // Trigger button — fires the port signal through DeviceLinkSystem
            var btn = new Button
            {
                Text = "[ ACTIVATE ]",
                MinWidth = 100,
            };
            btn.OnPressed += _ => OnInvokeLinkPort?.Invoke(capturedId);
            row.AddChild(btn);

            LinksList.AddChild(row);

            // Separator between port rows
            var sep = new PanelContainer
            {
                MinHeight = 1,
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f")),
            };
            LinksList.AddChild(sep);
        }
    }

    // ── Tab Switching ────────────────────────────────────────────────────────

    private void SwitchToDataTab()
    {
        _showingNotes = false;
        DataPanel.Visible = true;
        NotesPanel.Visible = false;
        LinksPanel.Visible = false;
        DatabasePanel.Visible = false;
        OverwatchPanel.Visible = false;
    }

    private void SwitchToNotesTab()
    {
        _showingNotes = true;
        DataPanel.Visible = false;
        NotesPanel.Visible = true;
        LinksPanel.Visible = false;
        DatabasePanel.Visible = false;
        OverwatchPanel.Visible = false;

        // Request fresh notes from server
        OnRequestNotes?.Invoke();
    }

    // #Misfits Add - Switch to the LINKS tab showing device link port controls
    private void SwitchToLinksTab()
    {
        _showingNotes = false;
        DataPanel.Visible = false;
        NotesPanel.Visible = false;
        LinksPanel.Visible = true;
        DatabasePanel.Visible = false;
        OverwatchPanel.Visible = false;
    }

    // #Misfits Add - Switch to the DATABASE tab showing the faction-shared knowledge base
    private void SwitchToDatabaseTab()
    {
        _showingNotes = false;
        DataPanel.Visible = false;
        NotesPanel.Visible = false;
        LinksPanel.Visible = false;
        DatabasePanel.Visible = true;
        OverwatchPanel.Visible = false;

        // Reset to folder list root and request a fresh state from the server
        _dbView = DbView.FolderList;
        _dbCurrentFolder = null;
        _dbCurrentSubfolder = null;
        _dbEditingDocumentId = null;
        OnRequestDatabase?.Invoke();
        RefreshDatabaseView();
    }

    private void SwitchToOverwatchTab()
    {
        _showingNotes = false;
        DataPanel.Visible = false;
        NotesPanel.Visible = false;
        LinksPanel.Visible = false;
        DatabasePanel.Visible = false;
        OverwatchPanel.Visible = true;
        RefreshOverwatchView();
    }

    public void UpdateOverwatch(OverwatchConsoleState? state, IEye? eye)
    {
        _overwatchState = state;
        _overwatchSourceEye = eye;
        _hasOverwatch = state != null;

        OverwatchTabButton.Visible = _hasOverwatch;
        TabBar.Visible = _hasNotebook || _hasLinkSource || _hasDatabase || _hasOverwatch;

        if (state == null)
        {
            _overwatchSourceEye = null;
            UpdateOverwatchCamera(null);
            if (OverwatchPanel.Visible)
                SwitchToDataTab();

            return;
        }

        OverwatchHeaderLabel.Text = state.MonitorTitle;
        UpdateOverwatchCamera(eye);
        RefreshOverwatchView();
    }

    // ── Notes Rendering ──────────────────────────────────────────────────────

    /// <summary>
    /// Rebuilds the notes list container with all note entries.
    /// </summary>
    private void RebuildNotesList(List<TerminalNoteEntry> notes)
    {
        NotesList.RemoveAllChildren();

        if (notes.Count == 0)
        {
            // Empty state message
            var emptyLabel = new RichTextLabel();
            var emptyMsg = new FormattedMessage();
            emptyMsg.PushColor(Color.FromHex(TermDimGreen));
            emptyMsg.AddText("No notes have been written on this terminal.");
            emptyMsg.Pop();
            emptyLabel.SetMessage(emptyMsg);
            NotesList.AddChild(emptyLabel);
            return;
        }

        foreach (var note in notes)
        {
            // Container for each note
            var noteBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 2,
            };

            // Header: author + timestamp
            var headerLabel = new RichTextLabel();
            var headerMsg = new FormattedMessage();
            headerMsg.PushColor(Color.FromHex(TermGreen));
            headerMsg.AddMarkupPermissive($"[bold]{note.AuthorName}[/bold]  —  {note.Timestamp:yyyy-MM-dd HH:mm}");
            headerMsg.Pop();
            headerLabel.SetMessage(headerMsg);
            noteBox.AddChild(headerLabel);

            // Body text
            var bodyLabel = new RichTextLabel();
            var bodyMsg = new FormattedMessage();
            bodyMsg.PushColor(Color.FromHex(TermGreen));
            bodyMsg.AddText(note.Text);
            bodyMsg.Pop();
            bodyLabel.SetMessage(bodyMsg);
            noteBox.AddChild(bodyLabel);

            // Delete button (only for the note's author)
            if (_viewerUserId != null && note.AuthorUserId == _viewerUserId)
            {
                var deleteBtn = new Button
                {
                    Text = "[ DELETE ]",
                    HorizontalAlignment = HAlignment.Left,
                };
                var noteId = note.Id; // capture for closure
                deleteBtn.OnPressed += _ => OnDeleteNote?.Invoke(noteId);
                noteBox.AddChild(deleteBtn);
            }

            // Dim separator between notes
            var sep = new PanelContainer
            {
                MinHeight = 1,
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f")),
            };
            noteBox.AddChild(sep);

            NotesList.AddChild(noteBox);
        }
    }

    // ── Submit Handler ───────────────────────────────────────────────────────

    private void HandleSubmit()
    {
        var text = NoteInput.Text?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(text))
            return;

        // #Misfits Tweak - Author name is now provided by the server (character entity name)
        OnSubmitNote?.Invoke(string.Empty, text);

        // Clear the input after submitting
        NoteInput.Text = string.Empty;
    }

    // ── Database Rendering ───────────────────────────────────────────────────
    // #Misfits Add - Faction-shared knowledge database tab. Stage 1 MVP:
    // folders → subfolders (1 level) → documents → revisions. Read/Write/Approve
    // gating is enforced server-side; client only hides controls based on flags.

    /// <summary>
    /// Receives a fresh database state from the server and re-renders the active view.
    /// </summary>
    private void RefreshOverwatchView()
    {
        if (_overwatchState == null)
            return;

        var search = OverwatchSearchBar.Text.Trim();
        var visibleEntries = string.IsNullOrWhiteSpace(search)
            ? _overwatchState.Personnel
            : _overwatchState.Personnel
                .Where(entry =>
                    entry.Name.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                    (!string.IsNullOrWhiteSpace(entry.JobTitle) &&
                     entry.JobTitle.Contains(search, StringComparison.OrdinalIgnoreCase)) ||
                    entry.Category.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                    entry.Number.ToString("D4").Contains(search, StringComparison.OrdinalIgnoreCase))
                .ToList();

        OverwatchNoPersonnelLabel.Visible = visibleEntries.Count == 0;
        OverwatchStopWatchingButton.Disabled = _overwatchState.WatchedNumber == null;
        SetTerminalMarkup(OverwatchRosterSummaryLabel,
            _overwatchState.Personnel.Count == 0
                ? $"[color={TermDimGreen}]No linked personnel detected.[/color]"
                : $"[color={TermGreen}]{visibleEntries.Count} of {_overwatchState.Personnel.Count} linked personnel visible.[/color]");

        var hasCurrent = false;
        if (_overwatchState.WatchedNumber != null)
        {
            foreach (var entry in _overwatchState.Personnel)
            {
                if (entry.Number != _overwatchState.WatchedNumber.Value)
                    continue;

                hasCurrent = true;
                break;
            }
        }

        if (hasCurrent)
        {
            SetTerminalMarkup(OverwatchStatusLabel,
                $"[color={TermGreen}]SOUND[/color] live   [color={TermGreen}]CAMERA[/color] live");
        }
        else if (_overwatchState.WatchedNumber != null && HasLastKnownOverwatchPosition())
        {
            SetTerminalMarkup(OverwatchStatusLabel,
                $"[color={TermGreen}]SOUND[/color] lost   [color={TermGreen}]CAMERA[/color] lost   [color={TermDimGreen}]Last known:[/color] {FormattedMessage.EscapeText(GetLastKnownOverwatchText())}");
        }
        else
        {
            SetTerminalMarkup(OverwatchStatusLabel,
                $"[color={TermGreen}]SOUND[/color] idle   [color={TermGreen}]CAMERA[/color] idle");
        }

        OverwatchPersonnelList.RemoveAllChildren();
        foreach (var group in visibleEntries
                     .OrderBy(entry => entry.CategorySortOrder)
                     .ThenBy(entry => entry.Name, StringComparer.OrdinalIgnoreCase)
                     .GroupBy(entry => entry.Category))
        {
            var groupName = group.Key;
            var bodyContents = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 6,
                Margin = new Thickness(8, 4, 8, 8),
                HorizontalExpand = true,
            };

            foreach (var entry in group)
            {
                bodyContents.AddChild(MakeOverwatchRow(entry));
            }

            var heading = new CollapsibleHeading($"{groupName} [{group.Count()}]")
            {
                MinHeight = 28,
                HorizontalExpand = true,
            };
            heading.AddStyleClass(ContainerButton.StyleClassButton);
            heading.Label.HorizontalExpand = true;
            heading.Label.HorizontalAlignment = HAlignment.Left;

            var body = new CollapsibleBody
            {
                HorizontalExpand = true,
                Children =
                {
                    bodyContents
                }
            };

            var collapsible = new Collapsible(heading, body)
            {
                HorizontalExpand = true,
                BodyVisible = !_overwatchGroupExpanded.TryGetValue(groupName, out var expanded)
                    ? string.IsNullOrWhiteSpace(search) || group.Any(entry => entry.IsCurrentTarget)
                    : expanded,
            };

            heading.OnToggled += args => _overwatchGroupExpanded[groupName] = args.Pressed;
            OverwatchPersonnelList.AddChild(collapsible);
        }
    }

    private Control MakeOverwatchRow(OverwatchConsoleEntry entry)
    {
        var active = entry.IsCurrentTarget;
        var rowStyle = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(active ? "#0a130a" : "#050805"),
            BorderColor = Color.FromHex(active ? TermGreen : "#0f3d0f"),
            BorderThickness = active ? new Thickness(4, 1, 1, 1) : new Thickness(1),
        };

        var row = new ContainerButton
        {
            HorizontalExpand = true,
            StyleBoxOverride = rowStyle,
        };
        row.OnPressed += _ => OnOverwatchAction?.Invoke(
            active ? OverwatchConsoleMessageType.Unwatch : OverwatchConsoleMessageType.Watch,
            entry.Number);

        var contents = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            Margin = new Thickness(6, 4, 6, 4),
        };
        row.AddChild(contents);

        var entryName = entry.Name ?? "UNKNOWN";
        var job = string.IsNullOrWhiteSpace(entry.JobTitle) ? "Unknown role" : entry.JobTitle!;

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        contents.AddChild(header);

        var title = new RichTextLabel { HorizontalExpand = true };
        SetTerminalMarkup(title,
            $"[color={TermGreen}][bold]> {FormattedMessage.EscapeText(entryName)}[/bold][/color] [color={TermDimGreen}]#{entry.Number:D4}[/color]");
        header.AddChild(title);

        var detail = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        SetTerminalMarkup(detail,
            $"[color={TermDimGreen}]{FormattedMessage.EscapeText(job)}[/color]");
        contents.AddChild(detail);

        var bottom = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        contents.AddChild(bottom);

        var healthBar = new ProgressBar
        {
            MinValue = 0f,
            MaxValue = 1f,
            Value = entry.Health,
            MinHeight = 12,
            HorizontalExpand = true,
        };
        UpdateHealthBarStyle(healthBar, entry.Health, entry.State);
        bottom.AddChild(healthBar);

        var state = new Label
        {
            Text = GetOverwatchStateLabel(entry.State),
            StyleClasses = { "monospace" },
            FontColorOverride = GetOverwatchStateColor(entry.State),
            MinWidth = 88,
            HorizontalAlignment = HAlignment.Right,
        };
        bottom.AddChild(state);

        return row;
    }

    private void UpdateOverwatchCamera(IEye? eye)
    {
        var hasFeed = eye != null;
        OverwatchCameraView.Eye = hasFeed ? _overwatchFeedEye : _overwatchDefaultEye;
        OverwatchCameraView.Visible = hasFeed;
        OverwatchCameraFallback.Visible = !hasFeed;

        var hasCurrent = TryGetCurrentOverwatchEntry(out _);
        var hasLastKnown = _overwatchState?.WatchedNumber != null && HasLastKnownOverwatchPosition();
        OverwatchCameraFallbackLabel.Text = hasCurrent
            ? "CAMERA FEED UNAVAILABLE"
            : hasLastKnown
                ? $"FEED LOST\nLAST KNOWN {GetLastKnownOverwatchText()}"
                : "NO ACTIVE CAMERA FEED";
        OverwatchSignalLabel.Text = hasCurrent
            ? "SECURE LINK ACTIVE"
            : hasLastKnown
                ? "LAST KNOWN LOCK"
                : "SECURE LINK STANDBY";
        OverwatchSignalLabel.FontColorOverride = Color.FromHex(hasCurrent || hasLastKnown ? TermGreen : TermDimGreen);
        SyncOverwatchFeedEye();
    }

    private void SyncOverwatchFeedEye()
    {
        if (_overwatchSourceEye == null)
            return;

        _overwatchFeedEye.Position = _overwatchSourceEye.Position;
        _overwatchFeedEye.Offset = _overwatchSourceEye.Offset;
        _overwatchFeedEye.Rotation = _overwatchSourceEye.Rotation;
        _overwatchFeedEye.Zoom = _overwatchSourceEye.Zoom;
        _overwatchFeedEye.DrawFov = _overwatchSourceEye.DrawFov;
        _overwatchFeedEye.DrawLight = _overwatchSourceEye.DrawLight;
    }

    private bool TryGetCurrentOverwatchEntry(out OverwatchConsoleEntry entry)
    {
        entry = default;

        if (_overwatchState?.WatchedNumber == null)
            return false;

        foreach (var personnel in _overwatchState.Personnel)
        {
            if (personnel.Number != _overwatchState.WatchedNumber.Value)
                continue;

            entry = personnel;
            return true;
        }

        return false;
    }

    private bool HasLastKnownOverwatchPosition()
    {
        return _overwatchState?.LastKnownX != null &&
               _overwatchState.LastKnownY != null &&
               !string.IsNullOrWhiteSpace(_overwatchState.LastKnownTimestamp);
    }

    private string GetLastKnownOverwatchText()
    {
        if (_overwatchState?.LastKnownX == null ||
            _overwatchState.LastKnownY == null ||
            string.IsNullOrWhiteSpace(_overwatchState.LastKnownTimestamp))
        {
            return "UNAVAILABLE";
        }

        return $"{_overwatchState.LastKnownX.Value:0.0}, {_overwatchState.LastKnownY.Value:0.0} @ {_overwatchState.LastKnownTimestamp}";
    }

    private void UpdateHealthBarStyle(ProgressBar bar, float health, MobState state)
    {
        bar.BackgroundStyleBoxOverride ??= new StyleBoxFlat(Color.FromHex("#081108"));
        bar.ForegroundStyleBoxOverride ??= new StyleBoxFlat(Color.FromHex(TermGreen));

        var foreground = (StyleBoxFlat) bar.ForegroundStyleBoxOverride;
        foreground.BackgroundColor = state switch
        {
            MobState.Dead => Color.FromHex("#7a1010"),
            MobState.Critical or MobState.SoftCritical => Color.FromHex("#c88412"),
            _ when health <= 0.35f => Color.FromHex("#c8c812"),
            _ => Color.FromHex("#33FF33"),
        };
    }

    private string GetOverwatchStateLabel(MobState state)
    {
        return state switch
        {
            MobState.Alive => "STABLE",
            MobState.Critical => "CRITICAL",
            MobState.SoftCritical => "DOWN",
            MobState.Dead => "DECEASED",
            _ => "STANDBY",
        };
    }

    private Color GetOverwatchStateColor(MobState state)
    {
        return state switch
        {
            MobState.Alive => Color.FromHex(TermGreen),
            MobState.Critical => Color.FromHex("#ffb347"),
            MobState.SoftCritical => Color.FromHex("#c8c812"),
            MobState.Dead => Color.FromHex("#d94b4b"),
            _ => Color.FromHex(TermDimGreen),
        };
    }

    public void UpdateDatabase(TerminalDatabaseState? state)
    {
        _databaseState = state;
        // #Misfits Change - DATABASE tab is shown whenever the server sent any database
        // state (which is now always, on every terminal). When the viewer lacks read
        // access, the panel itself renders a giant NO ACCESS message instead of being hidden.
        _hasDatabase = state != null;

        DatabaseTabButton.Visible = _hasDatabase;
        TabBar.Visible = _hasNotebook || _hasLinkSource || _hasDatabase || _hasOverwatch;

        if (state == null)
        {
            // No DB component on this terminal — make sure we aren't stuck on the tab.
            if (DatabasePanel.Visible)
                SwitchToDataTab();
            return;
        }

        // Header reflects faction display name + accent color
        DatabaseHeaderLabel.Text = state.DisplayName;
        if (TryParseColor(state.AccentColor, out var accent))
            DatabaseHeaderLabel.FontColorOverride = accent;

        // If the server included an open document, jump straight to the viewer
        if (state.OpenDocument != null)
        {
            _dbView = DbView.DocumentViewer;
            _dbEditingDocumentId = null;
        }

        RefreshDatabaseView();
    }

    /// <summary>
    /// Re-renders the database panel based on current navigation state (_dbView, etc.).
    /// </summary>
    private void RefreshDatabaseView()
    {
        if (_databaseState == null)
            return;

        // Reset visibility
        DatabaseBrowserScroll.Visible = false;
        DatabaseDocScroll.Visible = false;
        DatabaseEditor.Visible = false;
        DatabaseList.RemoveAllChildren();
        DatabaseActionsBar.RemoveAllChildren();

        // #Misfits Add - NO ACCESS sentinel: if the viewer doesn't match any faction
        // database's read access tags, the server returns a state with CanRead=false.
        // Render a giant red ACCESS DENIED panel and bail out (no folders/editor).
        if (!_databaseState.CanRead)
        {
            DatabaseBrowserScroll.Visible = true;
            DatabaseBreadcrumbLabel.SetMessage(FormattedMessage.FromMarkupPermissive("[color=#FF3333][bold]> ACCESS DENIED[/bold][/color]"));

            var noAccess = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 80, 0, 0),
            };
            noAccess.SetMessage(FormattedMessage.FromMarkupPermissive(
                "[color=#FF3333][bold][font size=32]NO ACCESS[/font][/bold][/color]\n\n" +
                "[color=#AA2222]No authorized faction database matches your ID.[/color]"));
            DatabaseList.AddChild(noAccess);
            return;
        }

        // Breadcrumb
        DatabaseBreadcrumbLabel.SetMessage(BuildBreadcrumb());

        switch (_dbView)
        {
            case DbView.FolderList:
                DatabaseBrowserScroll.Visible = true;
                RenderFolderList();
                break;
            case DbView.SubfolderList:
                DatabaseBrowserScroll.Visible = true;
                RenderSubfolderList();
                break;
            case DbView.DocumentList:
                DatabaseBrowserScroll.Visible = true;
                RenderDocumentList();
                break;
            case DbView.DocumentViewer:
                DatabaseDocScroll.Visible = true;
                RenderDocumentViewer();
                break;
            case DbView.EditorCreateFolder:
            case DbView.EditorCreateDoc:
            case DbView.EditorEditDoc:
                DatabaseEditor.Visible = true;
                RenderEditor();
                break;
        }
    }

    private FormattedMessage BuildBreadcrumb()
    {
        var msg = new FormattedMessage();
        msg.PushColor(Color.FromHex(TermDimGreen));
        msg.AddMarkupPermissive("[bold]> ROOT[/bold]");

        if (_databaseState == null)
        {
            msg.Pop();
            return msg;
        }

        if (_dbCurrentFolder != null)
        {
            var folder = FindFolder(_dbCurrentFolder.Value);
            if (folder != null)
                msg.AddMarkupPermissive($" / [bold]{FormattedMessage.EscapeText(folder.Name)}[/bold]");
        }
        if (_dbCurrentSubfolder != null)
        {
            var sub = FindSubfolder(_dbCurrentFolder, _dbCurrentSubfolder.Value);
            if (sub != null)
                msg.AddMarkupPermissive($" / [bold]{FormattedMessage.EscapeText(sub.Name)}[/bold]");
        }
        if (_dbView == DbView.DocumentViewer && _databaseState.OpenDocument != null)
            msg.AddMarkupPermissive($" / [bold]{FormattedMessage.EscapeText(_databaseState.OpenDocument.Title)}[/bold]");

        msg.Pop();
        return msg;
    }

    private DatabaseFolderSummary? FindFolder(Guid id)
    {
        if (_databaseState == null)
            return null;
        foreach (var f in _databaseState.Folders)
            if (f.FolderId == id) return f;
        return null;
    }

    private DatabaseSubfolderSummary? FindSubfolder(Guid? folderId, Guid id)
    {
        if (folderId == null) return null;
        var folder = FindFolder(folderId.Value);
        if (folder == null) return null;
        foreach (var s in folder.Subfolders)
            if (s.SubfolderId == id) return s;
        return null;
    }

    private void RenderFolderList()
    {
        if (_databaseState == null) return;

        if (_databaseState.Folders.Count == 0)
            DatabaseList.AddChild(MakeDimLabel("No folders. Create one to begin."));

        foreach (var f in _databaseState.Folders)
        {
            var capId = f.FolderId;
            var capName = f.Name;
            var deleted = f.Deleted;
            // #Misfits Add - Admin-marked folders can only be deleted/restored by Admin tier.
            var isAdmin = f.IsAdmin;
            var canModify = isAdmin ? _databaseState.CanAdmin : _databaseState.CanLeadership;

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6, HorizontalExpand = true };
            // #Misfits Tweak - Prefix with faction admin label badge for marked folders.
            var adminBadge = isAdmin ? $"[{_databaseState.AdminLabel}] " : string.Empty;
            var btn = new Button
            {
                Text = deleted ? $"{adminBadge}[ {capName} ] [DELETED]" : $"{adminBadge}[ {capName} ]",
                HorizontalExpand = true,
                Disabled = deleted,
            };
            btn.OnPressed += _ =>
            {
                _dbCurrentFolder = capId;
                _dbCurrentSubfolder = null;
                _dbView = DbView.SubfolderList;
                RefreshDatabaseView();
            };
            row.AddChild(btn);

            // #Misfits Change - Delete/restore gated on Leadership (or Admin if marked).
            if (!deleted && canModify)
            {
                var del = new Button { Text = "[ DEL ]", MinWidth = 60 };
                del.OnPressed += _ => OnDeleteDatabaseFolder?.Invoke(capId, null);
                row.AddChild(del);
            }
            if (deleted && canModify)
            {
                var rest = new Button { Text = "[ RESTORE ]", MinWidth = 80 };
                rest.OnPressed += _ => OnRestoreDatabaseEntry?.Invoke(capId, null, null, null);
                row.AddChild(rest);
            }

            DatabaseList.AddChild(row);
        }

        // #Misfits Change - Root folder creation is Leadership-only (Tier 7+). Tier 6
        // (write tag) cannot create root entries; they may only add inside existing roots.
        if (_databaseState.CanLeadership)
        {
            var create = new Button { Text = "[ NEW FOLDER ]", MinWidth = 120 };
            create.OnPressed += _ =>
            {
                _dbView = DbView.EditorCreateFolder;
                _dbEditorParentFolder = null;
                RefreshDatabaseView();
            };
            DatabaseActionsBar.AddChild(create);
        }
    }

    private void RenderSubfolderList()
    {
        if (_databaseState == null || _dbCurrentFolder == null) return;
        var folder = FindFolder(_dbCurrentFolder.Value);
        if (folder == null) { _dbView = DbView.FolderList; RefreshDatabaseView(); return; }

        // "Up" button to root
        DatabaseList.AddChild(MakeNavButton("[ .. ]", () =>
        {
            _dbView = DbView.FolderList;
            _dbCurrentFolder = null;
            RefreshDatabaseView();
        }));

        // Documents at folder root
        DatabaseList.AddChild(MakeDimLabel("─ DOCUMENTS ─"));
        var rootDocs = 0;
        foreach (var d in folder.Documents)
        {
            rootDocs++;
            DatabaseList.AddChild(MakeDocRow(d, folder.FolderId, null));
        }
        if (rootDocs == 0)
            DatabaseList.AddChild(MakeDimLabel("(none)"));

        // Subfolders
        DatabaseList.AddChild(MakeDimLabel("─ SUBFOLDERS ─"));
        if (folder.Subfolders.Count == 0)
            DatabaseList.AddChild(MakeDimLabel("(none)"));
        foreach (var s in folder.Subfolders)
        {
            var capSub = s.SubfolderId;
            var deleted = s.Deleted;
            // #Misfits Add - Subfolder lives under a root folder; inherits its Admin gating.
            var canModify = folder.IsAdmin ? _databaseState.CanAdmin : _databaseState.CanLeadership;
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6, HorizontalExpand = true };
            var btn = new Button
            {
                Text = deleted ? $"[ {s.Name} ] [DELETED]" : $"[ {s.Name} ]",
                HorizontalExpand = true,
                Disabled = deleted,
            };
            btn.OnPressed += _ =>
            {
                _dbCurrentSubfolder = capSub;
                _dbView = DbView.DocumentList;
                RefreshDatabaseView();
            };
            row.AddChild(btn);

            if (!deleted && canModify)
            {
                var del = new Button { Text = "[ DEL ]", MinWidth = 60 };
                del.OnPressed += _ => OnDeleteDatabaseFolder?.Invoke(folder.FolderId, capSub);
                row.AddChild(del);
            }
            if (deleted && canModify)
            {
                var rest = new Button { Text = "[ RESTORE ]", MinWidth = 80 };
                rest.OnPressed += _ => OnRestoreDatabaseEntry?.Invoke(null, folder.FolderId, capSub, null);
                row.AddChild(rest);
            }
            DatabaseList.AddChild(row);
        }

        // Action bar: new subfolder + new document
        if (_databaseState.CanWrite)
        {
            var newSub = new Button { Text = "[ NEW SUBFOLDER ]", MinWidth = 140 };
            newSub.OnPressed += _ =>
            {
                _dbView = DbView.EditorCreateFolder;
                _dbEditorParentFolder = folder.FolderId;
                RefreshDatabaseView();
            };
            DatabaseActionsBar.AddChild(newSub);

            var newDoc = new Button { Text = "[ NEW DOCUMENT ]", MinWidth = 140 };
            newDoc.OnPressed += _ =>
            {
                _dbView = DbView.EditorCreateDoc;
                _dbEditingDocumentId = null;
                RefreshDatabaseView();
            };
            DatabaseActionsBar.AddChild(newDoc);
        }
    }

    private void RenderDocumentList()
    {
        if (_databaseState == null || _dbCurrentFolder == null || _dbCurrentSubfolder == null) return;
        var folder = FindFolder(_dbCurrentFolder.Value);
        var sub = folder == null ? null : FindSubfolder(_dbCurrentFolder, _dbCurrentSubfolder.Value);
        if (folder == null || sub == null) { _dbView = DbView.SubfolderList; RefreshDatabaseView(); return; }

        DatabaseList.AddChild(MakeNavButton("[ .. ]", () =>
        {
            _dbCurrentSubfolder = null;
            _dbView = DbView.SubfolderList;
            RefreshDatabaseView();
        }));

        if (sub.Documents.Count == 0)
            DatabaseList.AddChild(MakeDimLabel("No documents in this subfolder."));

        foreach (var d in sub.Documents)
            DatabaseList.AddChild(MakeDocRow(d, folder.FolderId, sub.SubfolderId));

        if (_databaseState.CanWrite)
        {
            var newDoc = new Button { Text = "[ NEW DOCUMENT ]", MinWidth = 140 };
            newDoc.OnPressed += _ =>
            {
                _dbView = DbView.EditorCreateDoc;
                _dbEditingDocumentId = null;
                RefreshDatabaseView();
            };
            DatabaseActionsBar.AddChild(newDoc);
        }
    }

    private Control MakeDocRow(DatabaseDocumentSummary d, Guid folderId, Guid? subfolderId)
    {
        var capId = d.DocumentId;
        var deleted = d.Deleted;
        // #Misfits Add - Doc inherits Admin gating from its parent root folder OR its own IsAdmin flag.
        var parentFolder = FindFolder(folderId);
        var parentIsAdmin = parentFolder?.IsAdmin ?? false;
        var effectiveAdmin = parentIsAdmin || d.IsAdmin;
        var canModify = effectiveAdmin ? _databaseState!.CanAdmin : _databaseState!.CanLeadership;
        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6, HorizontalExpand = true };

        // #Misfits Add - Admin badge prefix on the doc row when this doc is independently Admin-protected
        // (parent's badge already shown on the folder row, so only flag standalone doc-admin here).
        var docAdminBadge = (d.IsAdmin && !parentIsAdmin) ? $"[{_databaseState!.AdminLabel}] " : string.Empty;
        var btn = new Button
        {
            Text = deleted
                ? $"{docAdminBadge}> {d.Title} [DELETED]"
                : $"{docAdminBadge}> {d.Title}  (rev {d.RevisionCount})",
            HorizontalExpand = true,
            Disabled = deleted,
        };
        btn.OnPressed += _ => OnOpenDatabaseDocument?.Invoke(capId);
        row.AddChild(btn);

        if (!deleted && canModify)
        {
            var del = new Button { Text = "[ DEL ]", MinWidth = 60 };
            del.OnPressed += _ => OnDeleteDatabaseDocument?.Invoke(capId);
            row.AddChild(del);
        }
        if (deleted && canModify)
        {
            var rest = new Button { Text = "[ RESTORE ]", MinWidth = 80 };
            rest.OnPressed += _ => OnRestoreDatabaseEntry?.Invoke(null, null, null, capId);
            row.AddChild(rest);
        }

        return row;
    }

    private void RenderDocumentViewer()
    {
        if (_databaseState?.OpenDocument == null)
        {
            // No doc loaded; bail to last known view.
            _dbView = _dbCurrentSubfolder != null ? DbView.DocumentList
                    : _dbCurrentFolder    != null ? DbView.SubfolderList
                    : DbView.FolderList;
            RefreshDatabaseView();
            return;
        }

        var doc = _databaseState.OpenDocument;

        var title = new FormattedMessage();
        title.PushColor(Color.FromHex(TermGreen));
        title.AddMarkupPermissive($"[bold]{FormattedMessage.EscapeText(doc.Title)}[/bold]");
        title.Pop();
        DatabaseDocTitle.SetMessage(title);

        var meta = new FormattedMessage();
        meta.PushColor(Color.FromHex(TermDimGreen));
        var lastRev = doc.Revisions.Count > 0 ? doc.Revisions[doc.Revisions.Count - 1] : null;
        var lastEditor = lastRev?.AuthorCharName ?? doc.CreatedByCharName;
        var lastTime = lastRev?.Timestamp ?? doc.CreatedAt;
        meta.AddText($"Author: {doc.CreatedByCharName}   |   Last edit: {lastEditor} @ {lastTime:yyyy-MM-dd HH:mm} UTC   |   Revisions: {doc.Revisions.Count}");
        meta.Pop();
        DatabaseDocMeta.SetMessage(meta);

        var body = new FormattedMessage();
        body.PushColor(Color.FromHex(TermGreen));
        body.AddMarkupPermissive(doc.Body);
        body.Pop();
        DatabaseDocBody.SetMessage(body);

        // Action bar: back, edit, rollback list
        var back = new Button { Text = "[ BACK ]", MinWidth = 80 };
        back.OnPressed += _ =>
        {
            _dbView = _dbCurrentSubfolder != null ? DbView.DocumentList
                    : _dbCurrentFolder    != null ? DbView.SubfolderList
                    : DbView.FolderList;
            RefreshDatabaseView();
        };
        DatabaseActionsBar.AddChild(back);

        if (_databaseState.CanWrite && !doc.Deleted)
        {
            // #Misfits Tweak - Edit on Admin-protected docs requires Admin tier (server enforces same).
            var docCanEdit = doc.IsAdmin ? _databaseState.CanAdmin : _databaseState.CanWrite;
            if (docCanEdit)
            {
                var edit = new Button { Text = "[ EDIT ]", MinWidth = 80 };
                edit.OnPressed += _ =>
                {
                    _dbView = DbView.EditorEditDoc;
                    _dbEditingDocumentId = doc.DocumentId;
                    RefreshDatabaseView();
                };
                DatabaseActionsBar.AddChild(edit);
            }
        }

        // #Misfits Add - [ EXPORT ] turns the current revision into a physical holotape
        // (placed into the actor's hand). Anyone with read access can export; deleted docs
        // are export-blocked client-side (server enforces leadership-only on deleted).
        if (!doc.Deleted)
        {
            var capExportDocId = doc.DocumentId;
            var export = new Button
            {
                Text = "[ EXPORT ]",
                MinWidth = 100,
                ToolTip = "Spawn a holotape carrying this document's title and body. Use it on a terminal or Pip-Boy to read on the go.",
            };
            export.OnPressed += _ => OnExportDatabaseDocument?.Invoke(capExportDocId);
            DatabaseActionsBar.AddChild(export);
        }

        if (_databaseState.CanLeadership && doc.Revisions.Count > 1)
        {
            // Show a rollback button per non-current revision
            foreach (var r in doc.Revisions)
            {
                if (r.RevisionNumber == doc.Revisions[doc.Revisions.Count - 1].RevisionNumber)
                    continue; // skip current
                var capRev = r.RevisionNumber;
                var capDocId = doc.DocumentId;
                var rb = new Button
                {
                    Text = $"[ ROLLBACK r{capRev} ]",
                    MinWidth = 120,
                };
                rb.OnPressed += _ => OnRollbackDatabaseDocument?.Invoke(capDocId, capRev);
                DatabaseActionsBar.AddChild(rb);
            }
        }
    }

    private void RenderEditor()
    {
        // Configure prompts and prefill
        DatabaseEditorTitleInput.Visible = _dbView == DbView.EditorCreateDoc || _dbView == DbView.EditorCreateFolder;
        DatabaseEditorBodyInput.Visible = _dbView != DbView.EditorCreateFolder;

        // #Misfits Add - Toolbar follows the same visibility rule as the body input
        // (hidden when creating a folder, since folders have no rich-text body).
        DatabaseEditorToolbar.Visible = _dbView != DbView.EditorCreateFolder;

        switch (_dbView)
        {
            case DbView.EditorCreateFolder:
                DatabaseEditorPrompt.Text = _dbEditorParentFolder == null
                    ? "NEW FOLDER (top-level)"
                    : "NEW SUBFOLDER";
                DatabaseEditorTitleInput.Text = string.Empty;
                DatabaseEditorTitleInput.PlaceHolder = "Folder name (max 64)";
                // #Misfits Tweak - Admin checkbox visible on ROOT folder creation for any
                // Leadership-tier (or higher) actor. Protection itself still gates editing/
                // deletion behind Admin tier — this lets heads protect their own stuff so peer
                // leadership can't trample it.
                var canShowAdminToggle = _dbEditorParentFolder == null
                                         && _databaseState != null
                                         && _databaseState.CanLeadership;
                DatabaseEditorAdminToggle.Visible = canShowAdminToggle;
                DatabaseEditorAdminToggle.Pressed = false;
                if (canShowAdminToggle)
                    DatabaseEditorAdminToggle.Text = $"[ \u2610  MARK AS {_databaseState!.AdminLabel} ]";
                break;
            case DbView.EditorCreateDoc:
                DatabaseEditorPrompt.Text = "NEW DOCUMENT";
                DatabaseEditorTitleInput.Text = string.Empty;
                DatabaseEditorTitleInput.PlaceHolder = "Title (max 64 chars)";
                DatabaseEditorBodyInput.TextRope = new Rope.Leaf(string.Empty);
                // #Misfits Tweak - Admin checkbox is also offered for documents (independent
                // per-document protection). Visible for Leadership tier or higher; the resulting
                // protection still requires Admin tier to bypass.
                var canShowDocAdminToggle = _databaseState != null && _databaseState.CanLeadership;
                DatabaseEditorAdminToggle.Visible = canShowDocAdminToggle;
                DatabaseEditorAdminToggle.Pressed = false;
                if (canShowDocAdminToggle)
                    DatabaseEditorAdminToggle.Text = $"[ \u2610  MARK AS {_databaseState!.AdminLabel} ]";
                break;
            case DbView.EditorEditDoc:
                DatabaseEditorPrompt.Text = "EDIT DOCUMENT (creates new revision)";
                var doc = _databaseState?.OpenDocument;
                DatabaseEditorBodyInput.TextRope = new Rope.Leaf(doc?.Body ?? string.Empty);
                DatabaseEditorAdminToggle.Visible = false;
                break;
        }

        var back = new Button { Text = "[ BACK ]", MinWidth = 80 };
        back.OnPressed += _ => HandleDatabaseEditorCancel();
        DatabaseActionsBar.AddChild(back);
    }

    private void HandleDatabaseEditorSubmit()
    {
        if (_databaseState == null) return;

        switch (_dbView)
        {
            case DbView.EditorCreateFolder:
            {
                var name = DatabaseEditorTitleInput.Text?.Trim() ?? string.Empty;
                if (string.IsNullOrEmpty(name)) return;
                // #Misfits Add - Admin flag only meaningful when toggle was visible (root + Admin tier).
                var markAdmin = DatabaseEditorAdminToggle.Visible && DatabaseEditorAdminToggle.Pressed;
                OnCreateDatabaseFolder?.Invoke(_dbEditorParentFolder, name, markAdmin);
                _dbView = _dbEditorParentFolder == null ? DbView.FolderList : DbView.SubfolderList;
                _dbEditorParentFolder = null;
                RefreshDatabaseView();
                break;
            }
            case DbView.EditorCreateDoc:
            {
                if (_dbCurrentFolder == null) return;
                var title = DatabaseEditorTitleInput.Text?.Trim() ?? string.Empty;
                var body = Rope.Collapse(DatabaseEditorBodyInput.TextRope);
                if (string.IsNullOrEmpty(title) || string.IsNullOrEmpty(body)) return;
                // #Misfits Add - Per-document Admin flag, only meaningful when toggle was visible.
                var docMarkAdmin = DatabaseEditorAdminToggle.Visible && DatabaseEditorAdminToggle.Pressed;
                OnCreateDatabaseDocument?.Invoke(_dbCurrentFolder.Value, _dbCurrentSubfolder, title, body, docMarkAdmin);
                _dbView = _dbCurrentSubfolder != null ? DbView.DocumentList : DbView.SubfolderList;
                RefreshDatabaseView();
                break;
            }
            case DbView.EditorEditDoc:
            {
                if (_dbEditingDocumentId == null) return;
                var body = Rope.Collapse(DatabaseEditorBodyInput.TextRope);
                if (string.IsNullOrEmpty(body)) return;
                OnEditDatabaseDocument?.Invoke(_dbEditingDocumentId.Value, body);
                _dbView = DbView.DocumentViewer;
                RefreshDatabaseView();
                break;
            }
        }
    }

    private void HandleDatabaseEditorCancel()
    {
        switch (_dbView)
        {
            case DbView.EditorCreateFolder:
                _dbView = _dbEditorParentFolder == null ? DbView.FolderList : DbView.SubfolderList;
                _dbEditorParentFolder = null;
                break;
            case DbView.EditorCreateDoc:
                _dbView = _dbCurrentSubfolder != null ? DbView.DocumentList : DbView.SubfolderList;
                break;
            case DbView.EditorEditDoc:
                _dbView = DbView.DocumentViewer;
                break;
        }
        RefreshDatabaseView();
    }

    /// <summary>
    /// #Misfits Add - Wraps the body input's current selection with the supplied open/close
    /// BBCode tags. If nothing is selected, inserts the tag pair at the cursor and places
    /// the caret between them so the user can immediately type the wrapped text.
    /// </summary>
    private void WrapBBCode(string openTag, string closeTag)
    {
        // Only meaningful when the body input is visible (document edit/create).
        if (!DatabaseEditorBodyInput.Visible)
            return;

        var lower = DatabaseEditorBodyInput.SelectionLower.Index;
        var upper = DatabaseEditorBodyInput.SelectionUpper.Index;

        if (upper > lower)
        {
            // Wrap selected text. InsertAtCursor replaces the current selection.
            var full = Rope.Collapse(DatabaseEditorBodyInput.TextRope);
            var selected = full.Substring(lower, upper - lower);
            DatabaseEditorBodyInput.InsertAtCursor(openTag + selected + closeTag);
        }
        else
        {
            // No selection: insert tag pair and drop the caret between the two tags.
            DatabaseEditorBodyInput.InsertAtCursor(openTag + closeTag);
            var caret = lower + openTag.Length;
            DatabaseEditorBodyInput.CursorPosition = new TextEdit.CursorPos(caret, TextEdit.LineBreakBias.Top);
        }

        DatabaseEditorBodyInput.GrabKeyboardFocus();
    }

    /// <summary>
    /// #Misfits Add - Strips every [tag] / [/tag] pattern from the body input. Useful
    /// when an author wants to start fresh after over-formatting.
    /// </summary>
    private void StripBBCode()
    {
        if (!DatabaseEditorBodyInput.Visible)
            return;

        var full = Rope.Collapse(DatabaseEditorBodyInput.TextRope);
        // Remove anything that looks like a BBCode tag: `[...]` not containing `[` or newline.
        var cleaned = System.Text.RegularExpressions.Regex.Replace(full, @"\[/?[^\[\]\n]+\]", string.Empty);
        DatabaseEditorBodyInput.TextRope = new Rope.Leaf(cleaned);
    }

    private void SetTerminalMarkup(RichTextLabel label, string markup)
    {
        label.SetMessage(FormattedMessage.FromMarkupPermissive(markup));
    }

    private RichTextLabel MakeDimLabel(string text)
    {
        var label = new RichTextLabel();
        var msg = new FormattedMessage();
        msg.PushColor(Color.FromHex(TermDimGreen));
        msg.AddText(text);
        msg.Pop();
        label.SetMessage(msg);
        return label;
    }

    private Button MakeNavButton(string text, Action onClick)
    {
        var btn = new Button { Text = text, HorizontalAlignment = HAlignment.Left, MinWidth = 80 };
        btn.OnPressed += _ => onClick();
        return btn;
    }

    private static bool TryParseColor(string hex, out Color color)
    {
        try { color = Color.FromHex(hex); return true; }
        catch { color = Color.White; return false; }
    }
}
