- type: job
  id: NCRMilitaryPoliceRecruit
  setPreference: true # #Misfits Tweak - visible in job selection
  hideWithoutJobWhitelist: true # #Misfits Tweak - visible in all menus
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-ncr-military-police-recruit
  description: job-description-ncr-military-police-recruit
  playTimeTracker: NCRMilitaryPoliceRecruit
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 72000 # 20 hours
  weight: 1
  startingGear: NCRMilitaryPoliceRecruitGear
  icon: "JobIconNcrLeader"
  supervisors: job-supervisors-ncr-militarypolice-recruit
  alwaysUseSpawner: true
  access:
  - NCR
  - NCRSGT
  - NCRLT
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRMilitaryPoliceRecruitGear
  equipment:
    head: N14ClothingHeadHatNCRSidecap
    back: N14ClothingBackpackNCR
    jumpsuit: N14ClothingMPUniformNCRDesert
    shoes: N14ClothingBootsCombatFilled
    belt: ClothingBeltNCR
    eyes: ClothingEyesGlassesSunglasses
    ears: N14ClothingHeadsetNCR
    pocket1: NCRMPKit_Set
    id: N14IDNCRDogtagMPRecruit
  innerClothingSkirt: N14ClothingOfficerUniformNCRDesert
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage:
    back:
      - N14BoxPlasticFilledMilitaryNCR
      - N14PoliceBaton
      - N14MagazinePistol45
      - N14MagazinePistol45

- type: playTimeTracker
  id: NCRMilitaryPoliceRecruit
